[package]
name = "rusty_falcon"
version = "0.4.0"
authors = ["CrowdStrike Inc"]
description = "Rust bindings for CrowdStrike Falcon API"
homepage = "https://github.com/CrowdStrike/rusty-falcon"
repository = "https://github.com/CrowdStrike/rusty-falcon"
readme = "README.md"
edition = "2021"
rust-version = "1.70.0"
license-file = "LICENSE"
keywords = ["api", "crowdstrike", "falcon", "security", "vulnerability"]
categories = ["api-bindings", "asynchronous", "web-programming"]

[dependencies]
# To satisfy minimal version check
openssl = "0.10.66"
# To satisfy minimal version check
openssl-sys = "0.9.103"
reqwest = { version = "0.12.8", features = ["json", "multipart"] }
serde = "1.0.210"
serde_derive = "1.0.210"
serde_json = "1.0.128"
thiserror = "2.0.0"
url = "2.5.2"

[dev-dependencies]
clap = { version = "4.5.19", features = ["derive"] }
tokio = { version = "1.40.0", features = ["rt-multi-thread", "macros"] }

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = "z"

[package.metadata.typos]
default = { extend-ignore-identifiers-re = [
    # ignore hexa data samples
    "[0-9a-fA-F][0-9a-fA-F]",
    "ot_",
    "_tto",
] }
files = { extend-exclude = [] }
