[package]
name = "rusty_falcon"
version = "0.3.0"
authors = ["CrowdStrike Inc"]
description = "Rust bindings for CrowdStrike Falcon API"
homepage = "https://github.com/CrowdStrike/rusty-falcon"
repository = "https://github.com/CrowdStrike/rusty-falcon"
readme = "README.md"
edition = "2021"
rust-version = "1.63"
license-file = "LICENSE"
keywords = ["api", "crowdstrike", "falcon", "security", "vulnerability"]
categories = ["api-bindings", "asynchronous", "web-programming"]

[dependencies]
# To satisfy minimal version check
openssl = "0.10.56"
# To satisfy minimal version check
openssl-sys = "0.9.91"
reqwest = { version = "0.11.18", features = ["json", "multipart"] }
serde = "1.0.183"
serde_derive = "1.0.183"
serde_json = "1.0.104"
url = "2.4.0"

[dev-dependencies]
clap = { version = "4.3", features = ["derive"] }
tokio = { version = "1.30", features = ["rt-multi-thread", "macros"] }
