name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Rust ${{matrix.rust}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
          components: rustfmt
      - run: |
          cargo test --lib --bins --examples --benches
      - run: |
          # We expect doc example to fail without Falcon Credentials
          cargo test --doc | grep 'Missing FALCON_CLIENT_ID environment variable.'
      - name: rustfmt
        run: |
          cargo fmt
          if [[ -n $(git status -s) ]] ; then
            echo "Running rustfmt leaves codebase in modified state."
            echo "Please run rustfmt or cargo fmt on your PR"
            git status -s
            git diff
            exit 1
          fi

  outdated:
    name: Outdated
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - run: cargo outdated --exit-code 1
